version: '3.8'

services:
  go-server:
    image: winvibe/server:latest
    build: .
    ports:
      - "4321:4321"
    restart: always
#    environment:
#      - TG_BOT_TOKEN=123456789:ABCdefGhIJKlmNoPQRsTyourTokenHere
#      - TG_CHAT_ID=543210987ам